version: '3'
services:

    start_page:
        build: './start_page'
        ports:
            - "3000:3000"

    login:
        build: './login'
        ports:
            - "3001:3000"
        env_file: 
            - "./env/mongodb.env"
            - "./env/crypto.env"

    registration:
        build: './registration'
        ports:
            - "3002:3000"
        volumes: 
            - ./uploads:/src/uploads
        env_file: 
            - "./env/mongodb.env"
            - "./env/email.env"
            - "./env/crypto.env"

    forgot_pass:
        build: './forgot_pass'
        ports:
            - "3003:3000"
        env_file:
            - "./env/email.env"
            - "./env/mongodb.env"
            - "./env/crypto.env"

    main_page:
        build: './main_page'
        ports:
            - "3004:3000"
        volumes: 
            - ./uploads:/src/uploads
        env_file: 
            - "./env/mongodb.env"

    upload_avatar:
        build: './upload_avatar'
        ports:
            - "3005:3000"
        volumes: 
            - ./uploads:/src/uploads

    add_friend:
        build: './add_friend'
        ports:
            - "3006:3000"
        volumes: 
            - ./uploads:/src/uploads
        env_file: 
            - "./env/mongodb.env"

    create_chat:
        build: './create_chat'
        ports:
            - "3007:3000"
        volumes: 
            - ./uploads:/src/uploads

    delete_chat:
        build: './delete_chat'
        ports:
            - "3008:3000"
        volumes: 
            - ./uploads:/src/uploads
        env_file: 
            - "./env/mongodb.env"

    change_info:
        build: './change_info'
        ports:
            - "3009:3000"
        volumes: 
            - ./change_info/public:/src/public
        env_file: 
            - "./env/mongodb.env"
            - "./env/crypto.env"

    chat:
        build: './chat'
        ports:
            - "3010:3000"
        volumes: 
            - ./uploads:/src/uploads
        env_file: 
            - "./env/mongodb.env"

    send_message:
        build: './send_message'
        ports:
            - "3011:3000"

    send_files:
        build: './send_files'
        ports:
            - "3012:3000"
        volumes:
            - ./uploads:/src/uploads

    change_members:
        build: './change_members'
        ports:
            - "3013:3000"

    event_bus:
        build: './event_bus'
        ports:
            - "3014:3000"

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - start_page
            - login
            - registration
            - forgot_pass
            - main_page
            - upload_avatar
            - add_friend
            - create_chat
            - delete_chat
            - change_info
            - chat
            - send_message
            - send_files
            - change_members
            - event_bus
