version: '3'
services:

    start_page:
        build: './start_page'
        ports:
            - "3000:3000"

    login:
        build: './login'
        ports:
            - "3001:3000"

    registration:
        build: './registration'
        ports:
            - "3002:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    #send_email:
    #    build: './send_email'
    #    ports:
    #        - "3003:3000"

    main_page:
        build: './main_page'
        ports:
            - "3004:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    upload_avatar:
        build: './upload_avatar'
        ports:
            - "3005:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    add_friend:
        build: './add_friend'
        ports:
            - "3006:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    create_chat:
        build: './create_chat'
        ports:
            - "3007:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    delete_chat:
        build: './delete_chat'
        ports:
            - "3008:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    chat:
        build: './chat'
        ports:
            - "3009:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    send_files:
        build: './send_files'
        ports:
            - "3010:3000"
        volumes:
            - ./main_page/uploads:/src/uploads


    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - start_page
            - login
            - registration
            #- send_email
            - main_page
            - upload_avatar
            - add_friend
            - create_chat
            - delete_chat
            - chat
            - send_files
            
