version: '3'
services:

    start_page:
        build: './start_page'
        networks: 
            - bridge
        ports:
            - "3000:3000"

    login:
        build: './login'
        networks: 
            - bridge
        ports:
            - "3001:3000"

    registration:
        build: './registration'
        networks: 
            - bridge
        ports:
            - "3002:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    #send_email:
    #    build: './send_email'
    #    ports:
    #        - "3003:3000"

    main_page:
        build: './main_page'
        networks: 
            - bridge
        ports:
            - "3004:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    upload_avatar:
        build: './upload_avatar'
        networks: 
            - bridge
        ports:
            - "3005:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    add_friend:
        build: './add_friend'
        networks: 
            - bridge
        ports:
            - "3006:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    create_chat:
        build: './create_chat'
        networks: 
            - bridge
        ports:
            - "3007:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    delete_chat:
        build: './delete_chat'
        networks: 
            - bridge
        ports:
            - "3008:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    change_info:
        build: './change_info'
        networks: 
            - bridge
        ports:
            - "3009:3000"
        volumes: 
            - ./change_info/public:/src/public

    chat:
        build: './chat'
        networks: 
            - bridge
        ports:
            - "3010:3000"
        volumes: 
            - ./main_page/uploads:/src/uploads

    send_files:
        build: './send_files'
        networks: 
            - bridge
        ports:
            - "3011:3000"
        volumes:
            - ./main_page/uploads:/src/uploads

    change_members:
        build: './change_members'
        networks: 
            - bridge
        ports:
            - "3012:3000"

    event_bus:
        build: './event_bus'
        networks: 
            - bridge
        ports:
            - "3013:3000"


    nginx:
        image: nginx:latest
        networks: 
            - bridge
        ports:
            - "8080:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - start_page
            - login
            - registration
            #- send_email
            - main_page
            - upload_avatar
            - add_friend
            - create_chat
            - delete_chat
            - change_info
            - chat
            - send_files
            - change_members
            - event_bus

networks: 
    bridge:
        driver: bridge
            
